name: AWS Docker Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: GitHub environment

      script:
        required: true
        type: string
        description: Location of the CDK script to run

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  aws-cdk-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: CDK Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: ingeno/greenfield-workflows/.github/actions/node-setup

      - name: Configure AWS Credentials
        uses: ingeno/greenfield-workflows/.github/actions/configure-aws-credentials
        with:
          aws-account-id: ${{ vars.AWS_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: CDK Deploy
        working-directory: infra/aws
        run: ${{ inputs.script }} ${{ vars.environment }}
