name: AWS Docker Deploy

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
        description: Name of the repository

      dockerfile:
        required: true
        type: string
        description: Location of the dockerfile

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  aws-docker-deploy:
    runs-on: ubuntu-latest
    name: Push to AWS ECR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: ingeno/aws-workflows/.github/actions/configure-aws-credentials@v2
        with:
          aws-account-id: ${{ vars.SHARED_SERVICES_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and Push image
        uses: ingeno/aws-workflows/.github/actions/docker-deploy@v2
        with:
          registry: ${{ vars.SHARED_SERVICES_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
          repository: ${{ inputs.repository }}
          tag: ${{ github.sha }}
          dockerfile: ${{ inputs.dockerfile }}
